def catering_message(engine):
    # engine.directories.clear_downloads(engine)
    # engine.driver.maximize_window()
    # tomorrow_unformatted = engine.date.get_future_date(0)
    # tomorrow_formatted = engine.date.format_date(tomorrow_unformatted, 'x/x/xxxx')
    # engine.routes.login_cfa_home(engine)
    # engine.routes.login_service_point(engine)
    # engine.routes.deferred_orders(engine, tomorrow_formatted)
    deferred_orders = engine.data.extract_deferred_orders(engine)
    message = engine.messages.catering_for_slack_groupme(engine, deferred_orders)
    engine.routes.login_groupme(engine)
    engine.routes.groupme_message(engine, message)