def southroads_reports(engine):
    yesterday_unformatted = engine.date.get_past_date(1)
    yesterday_formatted = engine.date.format_date(yesterday_unformatted, 'x/x/xxxx')
    engine.directories.clear_downloads()
    engine.driver.maximize_window()
    engine.routes.cfa.login_home(engine.driver, engine.config)
    engine.routes.cfa.cem_report_builder(engine.driver, engine.config)
    engine.routes.cfa.login_service_point(engine.driver, engine.config)
    engine.routes.cfa.daypart_activity(engine.driver, engine.config, yesterday_formatted)
    engine.routes.cfa.sales_activity(engine.driver, engine.config, yesterday_formatted)
    engine.routes.cfa.catering_orders(engine.driver, engine.config, yesterday_formatted)
    engine.driver.close()